### ISSUE TITLE
Booting to recovery after launching FourThree app

### ISSUE THREAD

**Issue by newdev8** [LukeZGD/FourThree-iPad2#1]
After following all the steps successfully on my iPad 2,2, when I launch the FourThree app the screen goes black and straight up boots to recovery instead of iOS 4.3.5.

**Comment by LukeZGD** [comment]
Yeah about that.. see here https://github.com/LukeZGD/Legacy-iOS-Kit/issues/589

FourThree has issues with cellular iPad 2, I have no plans on fixing it unfortunately. I will be adding this as a note in the script and readme

**Comment by MDX-Tom** [comment]
Well, my iPad 2,1 happens to do this as well.
Tried both launching the app and using the restore.sh script to boot 4.3.5, but both reboots into recovery.

**Comment by MDX-Tom** [comment]
This is the terminal output for booting 4.3.5 using the script.

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.16 (bc4db90)
* Platform: macos (15.2 - arm64)

* Device: iPad 2 (Wi-Fi) (iPad2,1 - k93ap) in Normal mode
* iOS Version: 6.1.3 (10B329)
* ECID: 1876303299343

 > Main Menu
[Input] Select an option:
1) Restore/Downgrade  4) Save SHSH Blobs    7) Other Utilities
2) Jailbreak Device   5) App Management	    8) Exit
3) FourThree Utility  6) Data Management
#? 3
 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.11.16 (bc4db90)
* Platform: macos (15.2 - arm64)

* Device: iPad 2 (Wi-Fi) (iPad2,1 - k93ap) in Normal mode
* iOS Version: 6.1.3 (10B329)
* ECID: 1876303299343

* FourThree Utility: Dualboot iPad 2 to iOS 4.3.x
* This is a 3 step process for the device. Follow through the steps to successfully set up a dualboot.
* Read the README here: https://github.com/LukeZGD/FourThree-iPad2

 > Main Menu > FourThree Utility
[Input] Select an option:
1) Step 1: Restore     3) Step 3: OS Install  5) Boot iOS 4.3.x
2) Step 2: Partition   4) Reinstall App	      6) Go Back
#? 5
[Log] Running iproxy for SSH...
[Log] iproxy PID: 29316
Creating listening port 6414 for device port 22
waiting for connection
* The default root password is: alpine
[Input] Enter the root password of your iOS device:
[Log] Checking if Step 1 is complete
New connection for 6414->22, fd = 5
waiting for connection
Requesting connection to USB device handle 379 (serial: 0203e8ab657e9dc33d57b77a966ea8551eff5d05), port 22
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Checking if Step 2 is complete
New connection for 6414->22, fd = 5
waiting for connection
Requesting connection to USB device handle 379 (serial: 0203e8ab657e9dc33d57b77a966ea8551eff5d05), port 22
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Checking if Step 3 is complete
New connection for 6414->22, fd = 5
waiting for connection
Requesting connection to USB device handle 379 (serial: 0203e8ab657e9dc33d57b77a966ea8551eff5d05), port 22
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
New connection for 6414->22, fd = 5
waiting for connection
Requesting connection to USB device handle 379 (serial: 0203e8ab657e9dc33d57b77a966ea8551eff5d05), port 22
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
[Log] Running FourThree Boot
New connection for 6414->22, fd = 5
waiting for connection
Requesting connection to USB device handle 379 (serial: 0203e8ab657e9dc33d57b77a966ea8551eff5d05), port 22
Warning: Permanently added '[127.0.0.1]:6414' (RSA) to the list of known hosts.
kern.version: Darwin Kernel Version 13.0.0: Wed Feb 13 21:37:19 PST 2013; root:xnu-2107.7.55.2.2~1/RELEASE_ARM_S5L8940X
kernel_base: 0x96e00000
Read image into buffer: 0x30c0000 length: 106496
Image information: LLB for k93ap, Copyright 2010, Apple Inc.
Image information: RELEASE
Image information: iBoot-1072.61
larm_init_tramp: 0x96e86018
Magic happening now. Device should wake up in 2.0 seconds.
Running the script '/Applications/FourThree.app/boot.sh' as root user...

* Save the terminal output now if needed. (macOS: Cmd+S, Linux: Ctrl+Shift+S)
* Legacy iOS Kit v24.11.16 (bc4db90)
* Platform: macos (15.2 - arm64)
