### ISSUE TITLE
Error in Step 2 (Partition): ls: cannot access /dev/disk0s3: No such file or directory

### ISSUE THREAD

**Issue by MDX-Tom** [LukeZGD/FourThree-iPad2#2]
<img width="845" alt="截屏2024-11-23 16 20 08" src="https://github.com/user-attachments/assets/ee06382e-5d60-4bc9-83b8-a73a3959ba8c">

Step 1 (Restore) works like a charm.
After 6.1.3 boots, I only completed setup.
However, Step 2 yields an error: ls: cannot access /dev/disk0s3: No such file or directory, but Step 2 continues to finish.
When I try Step 3, it yields the same error, says Step 2 is incomplete, and fails to proceed.

**Comment by MDX-Tom** [comment]
Step 2 can shrink the data partition of 6.1.3 to 15GB as I could see in the Settings App.
The script just could not find /dev/disk0s3.

**Comment by LukeZGD** [comment]
Delete all existing custom IPSWs and redo Step 1. Provide the full terminal output/log

**Comment by MDX-Tom** [comment]
Here's the terminal log for Step 1:
[20241123_193011.Default.w0t0p0.82FE445F-C990-4511-951F-4BCFF3960491.1051.572652282.log](https://github.com/user-attachments/files/17879493/20241123_193011.Default.w0t0p0.82FE445F-C990-4511-951F-4BCFF3960491.1051.572652282.log)

**Comment by MDX-Tom** [comment]
Here's the terminal log for Step 2:
[Step 2.log](https://github.com/user-attachments/files/17879509/Step.2.log)

**Comment by MDX-Tom** [comment]
What... As I proceed into Step 3, it seems to work.
Maybe it is the first IPSW that was faulty-created, making my redos fail either because I did not delete the custom IPSW before my redos.
