### ISSUE TITLE
Issue conclusion

### ISSUE THREAD

**Issue by MDX-Tom** [LukeZGD/FourThree-iPad2#3]
I use iPad 2,1 (Wi-Fi only), macOS 15.2 on an M1 Mac

Now the process can run through step 1 to 3, however there are still two main issues:

1. This is what happens after pressing the FourThree App icon on the homescreen after step 3:
The system reboots in 1 second, then shows a recovery screen (USB cable to iTunes icon), does not boot into 4.3.5.
Note that even if step 3 executes without error and the FourThree App is installed successfully,  the "/dev/disk0s3 not found" error in step 1 still occurs (see my log in the closed issue). I think the point might be here.

2. I tried the "Reinstall App" in the script menu, however the screen goes blank immediately. When I press the home button and unlock, all Apps on my home screen disappears, with newsletter and FourThree App left only.
This might indicate that the "Reinstall App" function might be dangerous.

3. The binary file "kloader" is included in the "dualbootstuff" pre-installed package. However if other cydia debs (i.e. kDFUApp) depends on the package "kloader", there will be a conflict as the binary file for the "kloader" package is already in the file system!

Now I'd like to wait until the script fixes errors. But if further tests is needed for these issues, I'll be glad to do it.

**Comment by LukeZGD** [comment]
1. If this occurs on the 2,1, it could be that the device is too new for iOS 4
2. Cydia needs to be opened at least once before using this option to avoid this issue

**Comment by MDX-Tom** [comment]
For 1, my model is A1395 (2011), and I'm pretty sure that my device was once on 4.3.3, the version I played on most of my time during my childhood hahaha :>

For 2, I've installed several tweaks already before I use this option. 
After my other apps were gone, I curiously mounted /dev/disk0s1 in SSH ramdisk and found that the FourThree App is the only app in /Applications. I guess that the app should be installed to /var/stash/xxx, which is not in /dev/disk0s1, and the main cause of my applications' disappearing might be that /Applications is not empty (and other apps in /var/stash/xxx could not be sym-linked to /Applications dir).

**Comment by MDX-Tom** [comment]
Update: I have tried a few more times with this, tried both 4.3.3 and 4.3.5. 

Each time I do: 
1) Fully delete and download latest Legacy-iOS-Kit release 
2) Execute Step 1 with no error 
3) Execute Step 2 and each time (except for one try yesterday when I closed the issue) it gives me the "/dev/disk0s3 not found" error, which makes Step 3 unable to execute.
It is very strange that I got pass Step 2 without the "/dev/disk0s3 not found" error only once over my 10+ attempts. Other attempts all result in this error.

There is one more thing, I SSHed into my device after Step 1, and I saw there is indeed no /dev/disk0s3 but there exists /dev/disk0s2s1, is this normal? 
<img width="736" alt="截屏2024-11-24 15 37 08" src="https://github.com/user-attachments/assets/7843fd83-724f-4087-81f2-b485e0080762">

**Comment by LukeZGD** [comment]
/dev/disk0s3 is supposed to show up **after** finishing step 2, so "/dev/disk0s3 not found" is normal in step 2. If you get /dev/disk0s3 not found in step 3, that is when the script will stop you

**Comment by MDX-Tom** [comment]
Yeah, I've just figured out /dev/disk0s3 is not the vital thing because I've just found out a way to let me go through Step 3.

I just have to turn on the log-to-file option in my mac terminal, only by this can I avoid a "/dev/rdisk0 not found" error at the end of Step 2.
<img width="844" alt="截屏2024-11-24 15 51 17" src="https://github.com/user-attachments/assets/5362ac26-379a-4ddc-9b04-7eabd4558b8e">

**Comment by LukeZGD** [comment]
Fixed 2 and 3 as of v24.11.17. As for 1, not much I can do as I mentioned earlier, so for now I'll close the issue now
