### ISSUE TITLE
FourThreeUtility bug

### ISSUE THREAD

**Issue by ahmalix** [LukeZGD/FourThree-iPad2#4]
[Terminal Output step 2.txt](https://github.com/user-attachments/files/18020321/Terminal.Output.step.2.txt)
[Terminal output step 3.txt](https://github.com/user-attachments/files/18020326/Terminal.output.step.3.txt)

I have redone step 2 many times but no luck,am I doing something wrong?

**Comment by LukeZGD** [comment]
looks like ill have to add waiting for disks in step 2.. ill push an update in a bit

**Comment by LukeZGD** [comment]
should be fixed in v24.12.07 now, just try step 2 again

**Comment by ahmalix** [comment]
Thank you that fixed it,but there's another issue now
Every time I click the FourThree app My iPad either restarts or goes into recovery mode and now I'm skeptical that despite having a iPad 2.2 model maybe it just doesn't support ios 4?

**Comment by LukeZGD** [comment]
unfortunately, it probably just doesn't support ios 4
